Support multiple topics consumer
streamnative/pulsar-dotpulsar pull request #2
Opened 2021-07-22 08:46 UTC by nodece

Issue: https://github.com/streamnative/support-tickets/issues/205

Current problems: the test is jammed.

2021-07-22 12:34 UTC, RobertIndie requested changes

2021-07-22 12:34 UTC, RobertIndie commented on src/DotPulsar/Internal/ConsumerBuilder.cs
> +                RegexSubscriptionMode = _regexSubscriptionMode
Here causes the test to fail.
We need to assign the subscription name here. 
Without explicitly setting the subscription name, the required field will be missing when the server parses the protobuf message. Lead to `UninitializedMessageException`.

Besides, I think we need to keep the original constructor of ConsumerOptions. This constructor ensures that the required fields are assigned values and also sets the default values for some fields

2021-07-29 07:17 UTC, RobertIndie requested changes

2021-07-29 07:17 UTC, RobertIndie commented on src/DotPulsar/Abstractions/IMessageId.cs
> +    public interface IMessageId : IComparable { }
Because this is a public interface, it is better to add some doc here.

2021-07-29 07:17 UTC, RobertIndie commented on src/DotPulsar/Extensions/ConsumerExtensions.cs
> -        public static async ValueTask Acknowledge(this IConsumer consumer, IMessage message, CancellationToken cancellationToken = default)
According to the [java client api](https://github.com/apache/pulsar/blob/1977a84179cda1c830617025f5f785563c068088/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L166), I think we need to keep both IMessage version and IMessageId version acknowledge method.

2021-07-29 07:17 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                    throw new Exception("Topic names list must be null when use topicsPattern");
Please use `ArgumentException`.

2021-07-29 07:17 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                    throw new Exception("Topic names list cannot be null");
Please use `ArgumentException`.

2021-07-29 07:17 UTC, RobertIndie commented on src/DotPulsar/ConsumerOptions.cs
> +        public static ISet<string> topicNames;
This field seems to be added by mistake.

2021-07-29 07:17 UTC, RobertIndie commented on src/DotPulsar/MessageId.cs
> -    public sealed class MessageId : IEquatable<MessageId>, IComparable<MessageId>
We need to keep `sealed` here.

2021-07-29 07:17 UTC, RobertIndie commented on tests/DotPulsar.IntegrationTests/ConsumerTests.cs
> +        public async void MultipleTopicsConsumer()
The test naming convention is [Method/Feature][Given/When]Something[Should/Then]ExpectedResult

2021-07-29 07:17 UTC, RobertIndie commented on tests/DotPulsar.IntegrationTests/ConsumerTests.cs
> +        public async void PatternTopicsConsumer()
The test naming convention is [Method/Feature][Given/When]Something[Should/Then]ExpectedResult

2021-07-29 07:17 UTC, RobertIndie commented on tests/DotPulsar.Tests/MessageIdTests.cs
> +    using System;
Please remove this line.

2021-07-29 07:17 UTC, RobertIndie commented on src/DotPulsar/Internal/NamespaceName.cs
> +        private readonly string tenant;
The private field should be prefixed with `_`. eg. `_tenant`.

2021-07-29 14:37 UTC, nodece commented on src/DotPulsar/Extensions/ConsumerExtensions.cs
> -        public static async ValueTask Acknowledge(this IConsumer consumer, IMessage message, CancellationToken cancellationToken = default)
Java can support the multiple ways, this is great, but I think that use the IMessage version is enough in dotnet client.

2021-07-30 01:44 UTC, RobertIndie commented on src/DotPulsar/Extensions/ConsumerExtensions.cs
> -        public static async ValueTask Acknowledge(this IConsumer consumer, IMessage message, CancellationToken cancellationToken = default)
I think the IMessageId version is more important than the IMessage version. Just like the original design, the IMessage ack could be the extension of the IMessageId ack.
In the multi topics consumer, when acknowledging with IMessageId, we could find the topic name using `TopicMessageId.getTopic`.

2021-08-03 14:27 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                    _topicsChangedListener = new TopicsChangedListener(
I think we could keep it simple and just loop with an await Task.Delay(..)

2021-08-03 14:34 UTC, RobertIndie requested changes

2021-08-03 14:34 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +    using Nito.AsyncEx;
Any reasons why using Nito.AsyncEx instead of the `System.Threading.ReaderWriterLock`?

2021-08-03 14:52 UTC, nodece commented on src/DotPulsar/Internal/Consumer.cs
> +                    _topicsChangedListener = new TopicsChangedListener(
Good idea.

2021-08-03 14:57 UTC, nodece commented on src/DotPulsar/Internal/Consumer.cs
> +    using Nito.AsyncEx;
When the code encounters `await`, the code changes it from the main thread to the worker thread, the `ReaderWriterLock` doesn't support unlocking from different threads, so we are using Nito.AsyncEx.

2021-08-05 02:56 UTC, nodece commented on src/DotPulsar/Internal/Consumer.cs
> +                    _topicsChangedListener = new TopicsChangedListener(
I think the current implementation is better, `TopicsChangedListener` is implemented using loop and Task with CancellationTokenSource, we can interrupt this listener at any time.

2021-08-06 03:34 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                    _topicsChangedListener = new TopicsChangedListener(
I think we can also interrupt the task using a simple loop with Task.Delay(). And in this way, we can share the same _cancellationTokenSource with the consumer. This makes it more convenient to manage tasks(like Monitor, AutoUpdatePartitions) in the consumer.
Here is an example of how to implement it: https://github.com/apache/pulsar-dotpulsar/blob/858067959a396e9f38b487d61b63001a932d92bc/samples/Producing/Program.cs#L50

2021-08-09 03:25 UTC, nodece commented on src/DotPulsar/Internal/Consumer.cs
> +                    _topicsChangedListener = new TopicsChangedListener(
@RobertIndie TopicsChangedListener supports the use of `Consumer._cts` , which is easy to manage, how about this.

2021-08-09 03:37 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                    _topicsChangedListener = new TopicsChangedListener(
If we do this, we don't need the `Stop` method of the listener.
To continue with the simplification, we can create a task like `Consumer.Monitor` directly without implementing the listener.

2021-08-09 09:10 UTC, nodece commented on src/DotPulsar/Internal/Consumer.cs
> +                    _topicsChangedListener = new TopicsChangedListener(
@RobertIndie Please review this changes.

2021-08-09 12:53 UTC, RobertIndie commented
Overall looks good to me. But there are some warnings when building the project. We should fix these warnings before merging to the codebase.
![image](https://user-images.githubusercontent.com/16974619/128707430-e9ce4557-779a-4298-9dbd-838e37e962ce.png)

Since many of these are code-style issues, I will release this feature to the customer first if you don't have time to fix these tomorrow.

2021-08-10 01:32 UTC, nodece commented
@RobertIndie Let's release a version first, and I'll fix the code style later

2021-08-10 07:37 UTC, nodece commented
@RobertIndie Warnings has been removed.

2021-08-17 10:08 UTC, RobertIndie requested changes

2021-08-17 10:08 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                using (_lock.ReaderLock())
It seems we can use `ConcurrentBag` here without using the read-write lock. FYI: https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentbag-1?view=net-5.0

2021-08-17 10:08 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                using (_lock.WriterLock())
The lookup operation is time-consuming. Maybe we can just lock when the topic partitions changed.

2021-08-17 10:08 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                        removeTopics.ForEach(n =>
Since pulsar only supports partitions expansion, we can disregard the remove topics case.

2021-08-17 10:08 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                        var oldTopics = _consumers.Keys;
This may result in getting the number of partitions from the partition sub topic like `test-partition-0`.

2021-08-17 10:08 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                var numberOfPartitions = await GetNumberOfPartitions(topic, _cts.Token).ConfigureAwait(false);
Since the lookup operation is time-consuming, it would be better if we can make here parallel.

2024-03-12 08:45 UTC, closed without merging