Fix problems of PR
streamnative/pulsar-dotpulsar pull request #6
Opened 2021-09-28 11:43 UTC by nodece

Signed-off-by: Zixuan Liu <nodeces@gmail.com>

2021-09-29 09:05 UTC, RobertIndie requested changes

2021-09-29 09:05 UTC, RobertIndie commented on src/DotPulsar/Abstractions/IConsumer.cs
>          /// <summary>
It seems that all the other properties we've added here are unnecessary.

2021-09-29 09:05 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +            var delay = (int) AutoUpdatePartitionsInterval.TotalMilliseconds;
We can simply remove this conversion process, right?

2021-09-29 09:05 UTC, RobertIndie commented on src/DotPulsar/Internal/ConsumerChannel.cs
> +                        continue;;
Although this solves the original problem, this seems to lead to a dead loop bug here.

2021-10-19 11:22 UTC, RobertIndie requested changes
There still seem to be problems with the current solution for receiving messages in the multi-topics consumer.

2021-10-19 11:22 UTC, RobertIndie commented on src/DotPulsar/Internal/Consumer.cs
> +                    var removed = _messagesQueue.TryDequeue(out var message);
I think there is still a problem with this solution. If one of the consumers receives a message, it has to wait until all the other consumers receive the message before it will continue to receive messages. This solution works with the existing tests, but the problem still needs to be solved, so maybe we need to add a test that covers this problem.

2021-10-28 14:58 UTC, nodece commented on src/DotPulsar/Internal/Consumer.cs
> +                    var removed = _messagesQueue.TryDequeue(out var message);
The `_messagesQueue` holds the `receiveTasks`, when one of the consumers receives a message, we will foreach the `_messagesQueue` to get the completed task, if no task, we will fetch new messages into `_messagesQueue`, and returns a message from first completed task.

2024-03-12 08:46 UTC, closed without merging